# Generated by Django 5.2.3 on 2025-07-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_default_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hide_recent_activity',
            field=models.BooleanField(default=False),
        ),
    ]
