# Generated by Django 5.2.3 on 2025-06-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_mealplan_created_by_recipe_author_mealplanday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealplanday',
            options={'ordering': ['day_number']},
        ),
        migrations.AddField(
            model_name='mealplan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mealplan_images/'),
        ),
        migrations.AddField(
            model_name='mealplanday',
            name='meals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
