# Generated by Django 5.2.3 on 2025-07-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_recipe_calories_recipe_carbs_recipe_fat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplement',
        ),
    ]
