# Generated by Django 5.2.3 on 2025-07-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_delete_supplement'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('dessert', 'Dessert'), ('vegan', 'Vegan'), ('keto', 'Keto')], default='lunch', help_text='Classify the recipe to improve filtering and UX.', max_length=20, null=True),
        ),
    ]
