# Generated by Django 5.2.3 on 2025-07-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, help_text='Short description or context about the recipe.', null=True),
        ),
    ]
