# Generated by Django 5.2.3 on 2025-07-28 19:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='goal',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('high_protein', 'Muscle Gain'), ('balance', 'Balanced Nutrition'), ('heart_healthy', 'Heart Healthy')], default='balanced', help_text='What is the main goal of this meal plan?', max_length=20),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
