# Generated by Django 5.2.3 on 2025-07-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_mealplan_goal_alter_mealplan_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='goal',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('high_protein', 'Muscle Gain'), ('balance', 'Balanced Nutrition'), ('heart_healthy', 'Heart Healthy')], default='balance', help_text='What is the main goal of this meal plan?', max_length=20),
        ),
    ]
